colorscheme iceberg

syntax on

set number
set expandtab
set tabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set wrapscan
set hlsearch
set showmatch matchtime=1
set guioptions+=a
set smartindent
set title
set clipboard=unnamed,autoselect
set backspace=indent,eol,start " for using delete on newer vim
" set cursorline カーソル移動遅い原因
set wildmode=list:longest
set whichwrap=b,s,h,l,<,>,[,]

set directory=/tmp

inoremap <silent> jj <ESC>

augroup source-vimrc
  autocmd!
  autocmd BufWritePost *vimrc source $MYVIMRC | set foldmethod=marker
  " autocmd BufWritePost *gvimrc if has('gui_running') source $MYGVIMRC 必要なさそう
augroup END

" //////////////
" plugin
" //////////////
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
" Plug 'neoclide/coc.nvim', {'branch': 'release'} 補完重い
" Plug 'neoclide/coc.nvim', {'tag': '*', 'branch': 'release'}
" Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
Plug 'airblade/vim-gitgutter'
Plug 'nathanaelkane/vim-indent-guides'

" " Comment out
Plug 'tomtom/tcomment_vim'
"
" Open github
Plug 'tyru/open-browser.vim'
Plug 'tyru/open-browser-github.vim'

" jsonnet hightlighting
Plug 'google/vim-jsonnet'

" rspec syntax highlighting
Plug 'keith/rspec.vim'

" terraform syntax
Plug 'hashivim/vim-terraform'

" php syntax highlighting
Plug 'StanAngeloff/php.vim'

" HTML, CSS, jS
Plug 'hail2u/vim-css3-syntax'

call plug#end()

" //////////////
" custom key map
" //////////////

let mapleader = "\<Space>"
let g:terraform_align=1
" let g:terraform_fold_sections=1

nnoremap <C-v> :<C-u>vsplit<CR>
nnoremap <Leader>p :<C-u>Files<CR>
nnoremap <Leader>o :<C-u>Ex<CR>
nnoremap <Leader>i :<C-u>Ag<CR>
nnoremap <Leader>u :<C-u>OpenGithubFile<CR>
vmap <Leader>u :<C-u>'<,'>OpenGithubFile<CR>
nnoremap <Leader>s :<C-u>w<CR>
nnoremap <Leader>q :<C-u>q<CR>
noremap <S-l> $
noremap <S-h> ^
nnoremap x "_x

let g:indent_guides_enable_on_vim_startup = 1
" autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3 キー入力遅い原因
" autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4

" use indent for pu
autocmd BufRead,BufNewFile *.pu set expandtab!

" php, html
" $VIMRUNTIME/syntax/php.vim
let g:php_baselib       = 1
let g:php_htmlInStrings = 1
let g:php_noShortTags   = 1
let g:php_sql_query     = 1
let php_parent_error_close  = 1
highlight Pmenu ctermbg=4
highlight PmenuSel ctermbg=1
highlight PMenuSbar ctermbg=4

filetype plugin on
